### ISSUE TITLE
OCR not indexed into fulltextsearch

### ISSUE THREAD

**Issue by giovacode** [R0Wi/workflow_ocr#154]
First of all, thank you for this great app, this is just awesome ! definitly a must have !!!

Here my problem, i'm using nextcloud AIO 2.0.3 (i had to modify nextcloud image to inject ocrmypdf into it).
your app works fine, but once OCR done, fulltextsearch with elasticsearch does't find text.

I have to manually call : 
`sudo docker exec -it nextcloud-aio-nextcloud php occ  fulltextsearch:index`

then only the text generated by OCR will be found.

This approach is not perfect because i have to manually re-index search, and this operation pass on ALL files.

can you do something to automate this? or do you have any tips agains this issue?

**Comment by R0Wi** [comment]
Hi @giovacode, thank's for your kind words 😃 

I also use the NC fulltextsearch app in my private cloud combined with the OCR app and I didn't notice any problems so far. The OCR app itself will create a new file version of the scanned file which should trigger the "file modified" event which in turn should be caught by the fulltext search app causing a reindex of that file. So to narrow the problem some questions from my side:

1. Do you use the [`fulltextsearch:live`](https://github.com/nextcloud/fulltextsearch/wiki/Commands#fulltextsearchlive) command to have your files indexed whenever changes are commited to the filesystem?
2. Does the indexing of "changed" files work for other filetypes? Like for example if you change a regular text file, is it indexed correctly afterwards?

Just a word on the docker setup: I just built a NC docker image with some "extended" packages here: https://github.com/R0Wi/nextcloud-docker-extended. The image will be automatically updated each night so that upstream changes from the official NC image are included. Maybe that could be interesting for you, too.

**Comment by R0Wi** [comment]
@giovacode any news on this?

**Comment by giovacode** [comment]
Hello @R0Wi 

Sorry for my late answer, i had to disconnect from computers for family reasons.

At this time i can just confirm that index doesn't works for me. I suspect this is because pictures are imported by my scanner, into a shared (external) folder. When i set a custom tag "TO-ORC" on  a new file, then OCR is done, the tag "OCR" is set to the file, but the file is not indexed into textSearch.

If i move the file into a indexed folder, the file is still not indexed. I then have to manually trigger occ fulltextsearch:index

I'll do more tests this week to answer your questions.

**Comment by R0Wi** [comment]
Hi @giovacode, does this issue still exist? If yes please provide a few more details otherwise I guess we can close this for now.

**Comment by R0Wi** [comment]
Closing for now due to lack of information. Will reopen if additional info arrives.
