### ISSUE TITLE
Integrate OCRmyPDF

### ISSUE THREAD

**Issue by R0Wi** [R0Wi/workflow_ocr#32]
Because of various issues regarding the compression of the PDF outputs an alternative tool should be used to process PDF files. We want to integrate [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF).

Issues are discussed [here](https://github.com/R0Wi/workflow_ocr/issues/22).

- [x] Update `README.md` for new install instructions
  * ~~Only `File create` supported?~~
  * Install `OCRmyPDF` dependency
  * Remove unnecessary dependencies
- [x] Change [PdfOcrProcessor.php](https://github.com/R0Wi/workflow_ocr/blob/ae6aa084a56a9f9280fa0c9f6105446fa7eacf9e/lib/OcrProcessors/PdfOcrProcessor.php) to use `OCRmyPDF`
  * Use a commandline wrapper
  * Use std-out for getting the pdf stream
- [x] Update tests accordingly
- [x] Change version to `1.20.1`
- [x] ~~Maybe find a way to configure commandline args (via flow parameter?)~~ (moved to https://github.com/R0Wi/workflow_ocr/issues/38)

**Comment by R0Wi** [comment]
First working version https://github.com/R0Wi/workflow_ocr/suites/1346287870/artifacts/21769925
(hope this artifact can be downloaded ? )

**Comment by thomasgg23** [comment]
Thanks, artifact can be downloaded.
Will test it on the weekend.

**Comment by thomasgg23** [comment]
I am getting the following message when trying to create a workflow MIME based.

![image](https://user-images.githubusercontent.com/2633051/96333848-95c28e00-106c-11eb-8615-2addf4305f37.png)

**Comment by R0Wi** [comment]
That's strange because i did not change anything regarding the UI. Are you on Nextcloud 20? And could you try to remove the "file renamed" condition?

**Comment by thomasgg23** [comment]
This one is working.

Will try some combinations

![image](https://user-images.githubusercontent.com/2633051/96334170-f05ce980-106e-11eb-8e91-5a7dc06f1bca.png)

**Comment by R0Wi** [comment]
Ok looks rather like a problem inside of the workflow engine of Nextcloud since these things aren't really influenced by the `workflow_ocr` app.

Let me know your results 👍

**Comment by bahnwaerter** [comment]
> I am getting the following message when trying to create a workflow MIME based.
> 
> ![image](https://user-images.githubusercontent.com/2633051/96333848-95c28e00-106c-11eb-8615-2addf4305f37.png)

@R0Wi, I've tested your first working version and can confirm the issue observed by @thomasgg23. The issue seems to be a bug in the Nextcloud workflow engine. If the `matches` operator is applied, the validation method `validateCheck` in the workflow engine throws in [line 91](https://github.com/nextcloud/server/blob/2a154f57ceeae89b15dfe166aff3a7916afde94c/apps/workflowengine/lib/Check/AbstractStringCheck.php#L91) the displayed value exception from the screenshot.

If the workflow is set up properly (eg. using the `is` operator), an OCR processing with the first working version of OCRmyPDF is possible. The OCR processing succeeds and does not show up any notable warnings or errors.

**Comment by R0Wi** [comment]
Thanks for testing @bahnwaerter. Will check that and eventually open a new issue at Nextcloud server repo 👍

**Comment by R0Wi** [comment]
@bahnwaerter FYI: the configuration currently mentioned in the docs will lead to an infinite loop, see https://github.com/R0Wi/workflow_ocr/issues/34#issuecomment-724689059

We should discuss some solutions ...
