### ISSUE TITLE
Use OCRmyPDF with original nextcloud docker image

### ISSUE THREAD

**Issue by bohrsty** [R0Wi/workflow_ocr#50]
We use nextcloud with the original [nextcloud docker image](https://hub.docker.com/_/nextcloud) and we don't want to build our own image, for full compatibility and simple updates. So there is no possibility to add/install the OCRmyPDF package and use it with the command line as done in this workflow_ocr app...

I could think about two setups (inspired by the docs of OCRmyPDF), using their docker image:

1. Use their [webservice](https://ocrmypdf.readthedocs.io/en/latest/docker.html#using-the-ocrmypdf-web-service-wrapper), although I know it is officially not for production use, but here it would only be internal use controlled by the workflow_ocr app:

> The OCRmyPDF web service wrapper is intended for demonstration or development. It provides no security, no authentication, no protection against denial of service attacks, and no load balancing.

2. Use their [batch hot folder mode](https://ocrmypdf.readthedocs.io/en/latest/batch.html#hot-watched-folders)

Both variants would require changes here and some config options in nextcloud. As far as I understand the code here, both variants wouldn't require the shell commands. For number 1 it would require a http client, that sends and receives the file with post method, number 2 has only the requirement of copying the file into input folder and take the processed file from output folder, the challenge here might be to determine when processing has finished...

Is there any chance that i.e. the webservice would be a supported option? Maybe I'm able to implement the http client part, but I cannot dive deep into the development of nextcloud apps and implement the required config options...

Kind regards

**Comment by bohrsty** [comment]
... in addition to the ideas above, there might be a simpler solution without the need of adding config options in the ui, but it is a bit hacky...
The mentioned issue only occur in pure docker environments, so we could give the required config options as environment variables to the nextcloud container and access them directly via php `get_env()` function inside the workflow_ocr code, where that decision needs to be made...

**Comment by R0Wi** [comment]
Hi @bohrsty thanks for your creative suggestions. @bahnwaerter and i are also considering an alternative installation method for the OCR backend which is easier to install and maintain. I think in general a solution which works both with native installation and inside your mentioned docker environment would be preferable. Since https://github.com/R0Wi/workflow_ocr/issues/49 mainly targets the same kind of problem i'd suggest to collect ideas regarding this problem at https://github.com/R0Wi/workflow_ocr/discussions/51 and then creating a new issue if we decide for one particular solution.
