### ISSUE TITLE
workflow delay

### ISSUE THREAD

**Issue by jkumeboshi** [R0Wi/workflow_ocr#73]
I've set the OCR workflow triggered by create/modify events, as stated in the docs.
When I load a new PDF the OCR workflow is not started immediately when the cron job runs.
Instead it starts after about 2 hours.

I did try with both a personal workflow in my profile and a site-wide workflow, with same results.

**Comment by R0Wi** [comment]
In general, like you already mentioned correctly, if the workflow conditions are met, the `OCR workflog` itself just adds a new job to the NC job-queue, which will then process the file asynchronously when the NC cron runs the next time.

To realize this behaviour a so called [`QueuedJob`](https://docs.nextcloud.com/server/latest/developer_manual/basics/backgroundjobs.html#types-of-background-jobs) was used. Usually, if such a job is added to the queue, it should run when the next NC cron is triggered. If that's not the case you should raise a new issue at the [main repository of Nextcloud](https://github.com/nextcloud/server). 

What you could do to gather additional information:

- Set your [loglevel](https://github.com/nextcloud/server) to `0`
- Add a new file so that the workflow will be triggered
- Ensure the file is added by inspecting the database Table `oc_jobs`
- Start the NC cron run (manually)
- Ensure that a log entry was written which says something like "STARTED -- Run...", "ENDED -- Run..."

Sorry but with the current information i think there is nothing we can do inside the app.

**Comment by jkumeboshi** [comment]
well, actually the job is created immediately in the oc_jobs.
But it executes immediately ONLY if I use command line "php cron.php" cron mode.
if I enable Ajax or Webcron modes the job is executed with a 2-3h delay.
Maybe because the web cron executes just 1 job at time, while CLI try to execute them all.
Anyway, as you said, isn't app's fault.

**Comment by R0Wi** [comment]
Would be an explanation that the job itself is queued correctly but has to wait since other jobs are executed first. Nevertheless if you have the opportunity i'd recommend the crontab approach for executing NC cron since it's much more reliable.

Closing this for now, please feel free to reopen if there's something else we can do.
