### ISSUE TITLE
Edit File Tags

### ISSUE THREAD

**Issue by fservida** [R0Wi/workflow_ocr#88]
It would be great if the app could change or add the file tags upon OCR completion, to allow for flows to be triggered once a file has been processed.
(eg from a "OCR Necessary" to a "OCR Done" tag)

**Comment by R0Wi** [comment]
Hi and thanks for your suggestion. This sounds like a really interesting idea to me but i'm not really sure if the app itself should handle tags. Since the app only integrates into the [workflow engine infrastructure](https://github.com/nextcloud/server/tree/master/apps/workflowengine) it would make more sense to me to add this feature there, then all workflow app would benefit from this.

You could also try the [Files automated tagging](https://apps.nextcloud.com/apps/files_automatedtagging) app and see if your workflow can be modelled with it. Did not try it but you could create a new workflow with something like "when file is changed and file system tag is tagged with OCR necessary -> tag with OCR done".
![image](https://user-images.githubusercontent.com/19730957/151303391-c6df3d92-f4c5-426f-8720-9d53b270180c.png)
Would be nice to get some feedback if that fits your needs.

If this does not work for you i think your feature request should be placed at https://github.com/nextcloud/server/issues.

**Comment by fservida** [comment]
Hello,
thanks for the feedback, indeed, I've tried to use the automated tagging but it is too wide as event catcher, and a simple move or rename triggers it, thus applying the tag.

I'll check if it's possible to extend directly the engine or if it's easier, at least in the meantime to maybe extend your app.

Additionally I've noticed that the tags applied by Automated Tagging do no trigger your flow if the flow is configured with "When: File is Tagged" and the newly applied tag as a file system tag condition
Is it something to be changed in your app or on automated tagging? (Manual tagging triggers the flow correctly)
![image](https://user-images.githubusercontent.com/501958/151424204-2c6c48a3-ee29-4714-8269-7fccac1fc199.png)

**Comment by fservida** [comment]
That is indeed what I'm trying to achieve, you have resumed the issue very well. I have already opened an issue about the chaining of OCR from Automated Tagging when run in the background in the main repo (https://github.com/nextcloud/server/issues/30900), will also open an issue for a generalised possibility of tag management "after" the flow, will link back here when done.

For your solution in the meantime, yes, that would meet my requirements, it would be awesome if it could be implemented. I may help with some of the dev, but I'm really unfamiliar with development for nextcloud and the whole app architecture unfortunately.

**Comment by R0Wi** [comment]
@fservida nice to hear that! If you would like to help i'd be very glad if you could imagine testing the new feature if i gave you a prerelease version.

Nevertheless please be patient with me since i first have to complete the feature request of https://github.com/R0Wi/workflow_ocr/issues/76. When that's done all the infrastructure will be there and this feature request here will be the next to be implemented. I will leave this issue open and track my progress here so stay tuned 😎

**Comment by fservida** [comment]
Hi!
Was just going over this again and saw your commits, awesome, if you want to pass me a prerelease build I'd love to test and give you feedback.

**Comment by R0Wi** [comment]
Thank's @fservida ! Currently it's work in progress but if i have a first beta i'll let you know :-)

**Comment by R0Wi** [comment]
Hi @fservida, a first beta version is available at https://github.com/R0Wi/workflow_ocr/suites/7491428931/artifacts/307588615 . Would be nice to get some feedback if you have some time for me. Let me know if you need help on how to setup the app.

**Comment by fservida** [comment]
Hello, awesome, will test this later today and let you know!

**Comment by fservida** [comment]
Hi, I've tested this couple days without issues about the new feature which is working great;

I'm still having other problems to fully implement the workflow I wanted, but those come from the files being on an external SMB share which has problems with workflow tagging app and I'm going to try and resolve them with the developers on the other side.

thanks for the work on feature!

**Comment by R0Wi** [comment]
Thank's for your feedback. I think you're talking about https://github.com/nextcloud/server/issues/30900, right? 😄 You're right, that's something inside the basic infrastructure of NC. If i have some time i could imagine investigate in that issue, too.

Regarding the new "Tag feature" mentioned here: i will add some tests and release it these days 👍
